### PR TITLE
Update BinaryBuilder URL

### PR DESCRIPTION
**Pull request by cielavenir**
not sure if we report this to staticfloat, since his number of repos are quite many.

### CODE REVIEW

**Comment by bicycle1885** [comment]
Thank you. I've copied the text from a wrong repository, so I need to fix that.

**Comment by cielavenir** [comment]
I actually meant that https://github.com/staticfloat/ZlibBuilder/blob/master/README.md is also old.
Would you mind contacting staticfloat about this? It looks like BinaryBuilder has moved from his own account to JuliaPackaging organization.

**Comment by cielavenir** [comment]
> Would you mind contacting staticfloat about this?

You don't have to do that anymore...

**Comment by cielavenir** [comment]
It looks like staticfloat noticed my PR and he has merged it.

**Pull request merged**
